USE [Library]
GO

SELECT BranchName, SUM(No_Of_Copies) AS CopiesPerBranch FROM BOOK_COPIES
INNER JOIN BOOK
ON BOOK_COPIES.BookID = BOOK.BookID
INNER JOIN LIBRARY_BRANCH
ON LIBRARY_BRANCH.BranchID=BOOK_COPIES.BranchID
WHERE Title='The Lost Tribe' 
GROUP BY BranchName