USE [Library]
GO

SELECT BOOK.Title AS BookTitle, BORROWERS.Name AS BorrowersName, BORROWERS.Address AS BorrowersAddress FROM LIBRARY_BRANCH
INNER JOIN BOOK_LOANS
ON BOOK_LOANS.BranchID = LIBRARY_BRANCH.BranchID
INNER JOIN BOOK
ON BOOK.BookID = BOOK_LOANS.BookID
INNER JOIN BORROWERS
ON BORROWERS.CardNo = BOOK_LOANS.CardNo
WHERE BranchName = 'Sharpstown' 
AND DueDate='2017-4-13'