USE [Library]
GO

SELECT BOOK.Title, BOOK_COPIES.No_Of_Copies FROM LIBRARY_BRANCH
INNER JOIN BOOK_COPIES
ON BOOK_COPIES.BranchID=LIBRARY_BRANCH.BranchID
INNER JOIN BOOK_AUTHORS
ON BOOK_AUTHORS.BookID = BOOK_COPIES.BookID
INNER JOIN BOOK
ON BOOK.BookID = BOOK_COPIES.BookID
WHERE BranchName = 'Central' AND AuthorName ='Stephen King'